# Generated by Django 4.2.9 on 2024-05-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banner',
        ),
    ]
