# Generated by Django 4.2.9 on 2024-05-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_image',
        ),
    ]
