# Generated by Django 4.2.9 on 2024-05-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
