# Generated by Django 4.2.9 on 2024-09-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_post_image_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='image',
        ),
    ]
