# Generated by Django 4.2.9 on 2024-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True, verbose_name='Email Address'),
        ),
    ]
