# Generated by Django 4.2.9 on 2024-05-16 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritetech',
            options={'ordering': ['type'], 'verbose_name': 'Favorite Tech', 'verbose_name_plural': 'Favorite Technologies'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.favoritetech', verbose_name='Favorite Tech'),
        ),
    ]
